name: Test, Build, and Publish to PyPI

on:
  release:
    types:
      - published

jobs:
  test-build-publish:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      # Install Poetry
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "export PATH=\"$HOME/.local/bin:$PATH\"" >> $GITHUB_ENV

      # Install dependencies
      - name: Install dependencies
        run: |
          poetry install --with test

      # Run tests
      - name: Run tests
        run: |
          poetry run pytest

      # Build the package
      - name: Build the package
        run: |
          poetry build

      # Publish the package to PyPI
      - name: Publish to PyPI
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
        run: |
          poetry publish --username __token__ --password $POETRY_PYPI_TOKEN_PYPI

